# Generated by Django 4.1 on 2023-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="main/static/main/image/avatar-default-icon.png",
                upload_to="",
                verbose_name="avatar",
            ),
        ),
    ]
