version: "3.8"

services:

  django:
    build: .
    container_name: django
    command: >
      sh -c " python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000 &&
              celery -A django_learn_ worker -l DEBUG"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/django_project
    depends_on:
      - db
  
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    container_name: db
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/postgresql/data/

  redis:
    image: redis:7.2-rc1-alpine
    container_name: redis


volumes:
  dbdata:
