# Generated by Django 4.1 on 2023-04-23 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_news",
                    models.CharField(max_length=128, verbose_name="Название"),
                ),
                (
                    "anons",
                    models.CharField(max_length=250, verbose_name="Кратное описание"),
                ),
                ("full_text", models.TextField(verbose_name="Текст статьи")),
                (
                    "data_create",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
